#!/bin/bash

set -e

[ "${RELEASE_BUILD}" != "TRUE" ] && exit 0

git config user.email "zeny-man@zeny.io"
git config user.name "zeny-man"

CI_RELEASE_VERSION=`date +"v%Y-%m-%d"`

cat > $HOME/.npmrc << EOF
---
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
EOF
chmod 600 $HOME/.npmrc

git commit -a -m "Update: ${CI_RELEASE_VERSION}"
git push --all

npm publish
