#!/bin/bash

set -e

git config user.name  "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

CI_RELEASE_VERSION=`date +"v%Y-%m-%d"`

cat > $HOME/.npmrc << EOF
---
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
EOF
chmod 600 $HOME/.npmrc

if [ -z "$(git status -s)" ]; then
  echo "No changes to commit"
  exit 0
fi

git commit -a -m "Update: ${CI_RELEASE_VERSION}"
git push --all

npm publish
