name: update

on:
  push:

  schedule:
    # Run at 12:00 JST
    - cron: '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: npm install
        run: npm install

      - name: update
        if: github.ref == 'refs/heads/master'
        run: |
          git submodule update --remote
          ./scripts/build
          ./scripts/ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}